const ShopActionTypes = {
	FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
	FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
	FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
	SYNC_COLLECTIONS_START: "SYNC_COLLECTIONS_START",
	SYNC_COLLECTIONS_SUCCESS: "SYNC_COLLECTIONS_SUCCESS",
	SYNC_COLLECTIONS_FAILURE: "SYNC_COLLECTIONS_FAILURE"
};

export default ShopActionTypes;
